### ISSUE TITLE
New idea for the app

### ISSUE THREAD

**Issue by sturrock** [AU-COVIDSafe/mobile-ios#14]
Hi there,

I have a very interesting and simple idea for the app which will hit three birds with one stone and force people to use it more, giving more accurate data.

Send an email to - **git@sturrock.com.au** to hear about the idea.

**Comment by KonajuGames** [comment]
If it is so simple, just write it here. Unless you're trying to extract money for it (which won't happen) or don't want it investigated (most likely outcome).

**Comment by sturrock** [comment]
I'm not looking for money, I'd rather speak with the developer over the phone to explain. 

The idea comes from filling your details out manually when entering a venue, some venues have paper sign-in, some have a QR code you scan (where most people don't actually fill out). So why not have a QR system in the app where a venue MUST scan your QR code in-order to enter. You cannot enter the venue unless you have the covid app. At that point the bluetooth will also make the connection with everyone around, plus you'll have an actual log of who was at what venue and at what time. 

I don't know how the privacy side of this would work, which is why I wanted an email so we could have a phone chat about it.

**Comment by KonajuGames** [comment]
The legislation as passed would not allow this because it forbids any place to deny entry if the person does not have the app installed. This is not a tech issue. It's the legislation that went along with the app.

**Comment by sturrock** [comment]
You wouldn't have to deny entry, it's just another tool business could use to track people entering if they wanted to. If it was all integrated into the covid app it would make life so much easier. Just an idea anyways, take it or leave it.

**Comment by newhoggy** [comment]
For venues that are currently require customers to record contact details in a log book for the visit, it's reasonable give an exemption for people who have the app installed.  Doing it this way does not contravene the law and probably only requires a change in the regulation of the relevant state.

The QR code should only identify the software as being legitimate (not a fake screenshot) and perhaps also the version of the software.  It should not contain any information that identifies the user.

**Comment by sturrock** [comment]
You use bluetooth to track their unique id so then you can trace back to who they have been in contact with. 
So just make it when you scan the QR code, it literally just inserts a new record that you have been in-contact with that venue (same as if the bluetooth tacked it). There's no law changing or anything that needs to happen. Just build the feature and move on, most people would like it, and if not.... then they wont have to use it.

**Comment by mediaprophet** [comment]
i've worked on this sort of idea for a while, whilst noting - RFID/NFC Wristbands provides a means to get off US OSs. 

BUT; phones already do a fair bit of tracking for reasons other than health (not health data just plain old pervasive surveillance / tracking).  

If the department(s) send notifications as RDF (perhaps using schemaorg markup ie; https://schema.org/SpecialAnnouncement  ) info (ie: https://www.nsw.gov.au/covid-19/latest-news-and-updates ) then existing apps on phones could notify persons who've potentially been exposed, recommending they make themselves known to authorities and get tested.

**Comment by newhoggy** [comment]
> You use bluetooth to track their unique id so then you can trace back to who they have been in contact with.
> So just make it when you scan the QR code, it literally just inserts a new record that you have been in-contact with that venue (same as if the bluetooth tacked it). There's no law changing or anything that needs to happen. Just build the feature and move on, most people would like it, and if not.... then they wont have to use it.

A potential downside to this is someone who dislikes the app or wants to cause trouble can DDoS the contact database by sharing QR codes on the Internet to scan them in without actually visiting the venue.

**Comment by mediaprophet** [comment]
AFAIK there's a couple of problems linked to the dependency model on BLE.
Using NFC/QRCodes as identifiers is more effective; but the 'devil in the
detail' is how the 'back-end' works, noting, that for the most part
activity data isn't healthcare data, and that facebook could easily &
rapidly roll-out functionality to encourage people to build a 'page' for
their business and print the QR code thing; providing a compliant solution
for businesses / premises as an option to 'check-in, with facebook' (or
similar); underneath that, is bigger problems..

noting also - kinda important the receiver is able to verify the fact that
someone has indeed logged in, and not just pretended to; or did so with
someone elses identifier.

old thoughts included
https://twitter.com/SailingDigital/status/1280052809971331073

background includes;
https://www.facebook.com/rdf.webid/photos/a.375218595947379/379342372201668
 |
https://www.w3.org/community/credentials/2014/08/06/call-for-participation-in-credentials-community-group/
& https://lists.w3.org/Archives/Public/public-webpayments/2014May/0033.html
which in-turn led to:
https://twitter.com/SailingDigital/status/1270277195831717888 and
https://www.microsoft.com/en-us/security/business/identity/own-your-identity
 | https://identity.foundation/ (amongst the many links); but i did the
work as a citizen from 2010 in particular, to support concepts (even when
unpaid, noting employees of GOV & VCs didn't really support the data-needs
of citizens - not part of corporations act, but it is a complex issue even
now so many years on: https://www.youtube.com/watch?v=VUMvObLKaaw |
https://www.youtube.com/watch?v=6lasZCwYijU )  ( as described:
https://drive.google.com/file/d/1SqUrWs_Ynu5401taK7Fv6Ck2v_lMnky4/view )
noting: https://www.youtube.com/watch?v=dpsFIVOMg4g&feature=youtu.be&t=6937
- my name on a list from years earlier:
https://www.youtube.com/watch?v=gZB6d-4klmU  (was called RWW

Old conference i put together (click on faces to see their backgrounds)
https://2017.trustfactory.org/  and NB also:
https://www.slideshare.net/Ubiquitousau/

I am strongly against 'global identity infrastructure' and believe it is
vitally important to have domestic solutions that support separation of
powers, rule of law and an array of other sophisticated considerations that
fit into what i term an inter-domestic approach (not silos); but as this is
not in place, and as banks cannot presently provide a principal / principal
agent relationship between a person and their online data/AI service
(domestically - aka "knowledge bank") there are now far fewer options; when
its very important to get better solutions in place ASAP.

I commend Gov for having made something domestically, but i do think it is
increasingly important to 'life the game'.  At a simple level, it could be
as easy as publishing https://www.linked.data.gov.au/ (RDF) so
international platforms can create an extensible alert system for phone
owners; at a far more sophisticated level, there's an array of other
options that could achieve much more; but the provenance on that stuff
counts, as its both specialised and if done in a 'fit for purpose' manner -
engenders provenance evaluation in a manner that's able to address any
matters that may otherwise be complicated by 'legal insufficiencies' (
http://parlview.aph.gov.au/mediaPlayer.php?videoID=510991&operation_mode=parlview
).

Cheers.

Timo.

**Comment by mediaprophet** [comment]
I forgot to note; present WIP is looking at solutions for noncovid areas of
AUS (&NZ?) To support tourism destinations with higher degree of certainty
/ insurability, etc.  Part of that likely requires a covid19 test to be
presentable prior to travel arrangements / bookings.

Earlier credentials work led to:
https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html

Which is something that could be done in a way that uses domestic crypto
and is independent to activity tracking.

Note also, it's important to ensure kids are able to participate in
society. which is part of the considerations about wristbands, noting
again, the problem isn't really about the lack of endpoint identifiers. IMO.

**Comment by MartinGardiner** [comment]
Heard Vic Premier speaking about QR-Code for logging visits just yesterday. Just a quick way to log, Andrews did mention it would be good to have a standard format, and delivered via the existing App, getting the phone number from the device seems like a very good idea.

The first thing to realize is THIS IS WAR. Seriously, we need to KILL EVERY LAST CELL of this virus to truly return to a pre-COVID life. A few infections a day still kills the economy. No parent is going to risk their family to goto a restaurant, the pictures, the gym for a workout etc. while a person a day gets infected. Its is OK if your healthy and don't give a shit about everyone else, but a decent person would not unnecessarily risk exposure for fear of infecting someone else.

I am in Victoria, locked down forever because of selfish people who put their 'lifestyle' above others, because they aren't in the danger zone. 

If you don't wish to run the app, you stay locked down, you don't leave the house. You go out without the App, you get a leg tie and stay locked down. This is firstly costing the Victorian economy $2b a week. ONE person can infect dozens within a few days, 

And then we have the emotional damage, the damage to our children's education and social growth. The damage to business for every day this continues. Go out without the App, without precautions, if not an accident - put the fuckers in a COVID prison, and if they live, they can go home. OK OK, a little carried away, but listening to SkyNews (News - isn't that false advertising) and all the other COVID supporters egging idiots to break the rules, not wear masks, do what you want. Those traitors should, like any other war time, be put away for the damage they are causing.

The say let ignore the virus, let the business open, pretending to say they wish to help. Liars or idiots. Cheap sunsashionlist journalism for the sake of negotiating their next contracts, at the expense of Victorians, and the business that operate here. 

Plus: If the App changed the LOCK screen to show the the QR Code that would be inform the user it is running, which is going to be another problem. I know you can do it from IOS Springboard BUT Apple will not allow such a App in the the App Store, but they can make an exemption, after all changing the Bluetooth spec was very naughty, and they should have reversed the change in days, instead of it taking 6 months to get a complicated working solution.

Make it work and save people first - increase complexity while people are not hurting, are not dying.

The QR Code should be simple as, just the information you would give on entering a store. Absolutely no encryption, no one can copy it unless you hand tghm your phone, and business don't need a special device to read it. 
That say, write a simple Android app to log and upload to a google Drive desposity, so anybody can record entry with a cheap android phone. Maybe the source, and the firmware can be altered to just do this function.

The QR Code on the LOCK screen also allows police and other to check your running the app because you can just wave your phone at anyone and confirm you running it. I understand the police can also have the ability too approach a group knowing how many people running the app, and people in the group can wave displaying the locked screen.

Also I even think everyone should be ask (MADE) to run google maps tracing, so contact tracing is easier to do, because you hae a record of where you have been.

**Comment by mediaprophet** [comment]
QR Code is essentially a URI & IMO the ability to generate some sort of URI isn't really the problem.

Identity systems need infrastructure built upon trustworthy foundations, that takes years to produce, and isn' just about software.   Seems the problem is that other decisions have been made nowtherefore limiting what can now be done quickly.

**Comment by sturrock** [comment]
I feel like you guys aren't getting the idea... currently the app records when a person comes into contact with another person via bluetooth, so just made another feature where you can scan a QR code when you enter a business and it just creates a record to say you were at that location. I don't get what the problem is, anyone would think this is rocket science. Theres no infrastructure no nothing. If you just put that in, most businesses would use it, since their currently doing it with paper or google forms... am i missing something?

**Comment by sturrock** [comment]
It doesn't matter anyway now cause you already missed the boat. No one uses this app anymore cause you didn't give them a reason too, which is a shame cause it would have solved the problem if businesses had the QR feature.

**Comment by aktfire747** [comment]
Canberra is using some of this idea with the Check in CBR app where you scan a QR code at the entrance of the business and your data is sent to the ACT Department of Health, (I think it is) and the app stores the time, date and location of the scan. Only thing not all businesses have the QR code and some like Woolworths have their own one that doesn't work with the app Check In CBR app anyway!

**Comment by mediaprophet** [comment]
CBR strategy sounds like a good start.

There are commercial Globalists looking for cybersecurity / national
security gaps / opportunities brought about by domestic dishonesty.  As
much as a prohibition against investigation domestically has been set out,
we don't want a national digital identity infrastructure fabric run by
offshore commercial entities, well, not from a sovereignty point of view
Anyhow.

I'm sure there's lots of cash up for grabs, but at the end of the day, it
is potentially a fastly sophisticated new form of slavery.

So, I'd prefer to see domestic problems sorted out here, understanding that
may now be impossible.


Timo.

**Comment by covidsafe-team** [comment]
Thanks @sturrock  for your considered feedback. As [noted here](https://github.com/AU-COVIDSafe/mobile-android/issues/30#issuecomment-739706281 ) COVIDSafe will continue to focus on Bluetooth tracing. QR Code integration is not currently within the scope of COVIDSafe.
