### ISSUE TITLE
Efficacy of two locked iPhones

### ISSUE THREAD

**Issue by HendX** [AU-COVIDSafe/mobile-ios#29]
In the updated efficacy graph, it is claimed that COVIDSafe using Herald will perform at a rate of "Excellent" between two locked iPhones (i.e. "80-100%").

![image](https://user-images.githubusercontent.com/525190/100560068-876ebf80-3304-11eb-8bb0-569a4c6d1457.png)

Since this is technically not possible, can you please outline how you arrived at this result, including the methodologies and raw data to achieve this result?

**Comment by covidsafe-team** [comment]
Hi @HendX some additional info on Herald testing is available here https://vmware.github.io/herald/results/herald-2020-11-28

**Comment by HendX** [comment]
Thank you. Unfortunately this doesn't satisfy my initial question as it makes a very bold claim with no evidence.

It would be in the general interest of the public for DTA to publish its own testing methodologies and results.

For example, does this result rely on an Android phone also being nearby?

Are DTA claiming that two locked iPhones will exchange keys with 100% reliability, in any situation?

**Comment by wabzqem** [comment]
Two locked iPhones which have not previously exchanged data (or both have rotated macs since last seeing each other) do not appear to exchange keys. I installed COVIDSafe herald on two iPhones (iPhone 6S, iPhone SX Max), and followed this process several times, resulting in periods (30min+) where the devices were in range but did not exchange data.

To reproduce:
- Run COVIDSafe herald on two iOS devices. Background & lock devices. Do not let other devices interfere (recommend using their own service uuid)
- Take devices out of range of each other and wait 30 minutes (or just launch + lock out of range)
- Bring the devices back into range, but do not unlock or wake the screen
- Wait 30 minutes
- Check logs, and observe that no exchanges have taken place until after one device is unlocked.

If two iPhones are already exchanging contacts, they will continue to do so pretty much indefinitely (even when locked) - but this isn’t always realistic. Please let me know if you can't reproduce this scenario or if there's something flawed about this process.

Please document and publicise in detail your test methodology (do not just link to herald, there are very suspicious steps in some of their testing) so that the community can help define useful test scenarios as well. Thanks!

**Comment by tonyarnold** [comment]
Reading the documentation, Herald seems to have extremely similar limitations to those seen in the UK's rejected contact tracing app, ie. needing an Android device to be proximal to locked iOS devices for them to record a contact - see https://vmware.github.io/herald/bluetooth/os#os-hides-underlying-bluetooth-activity. 

It also appears that testing was only done under very controlled conditions in an office environment. Isn't this what caused the UK to reject these same test results and methodology as unworkable in real world scenarios?

Is this an updated version of what was used in the UK's app? It's by the same team at VMware, right?

**Comment by covidsafe-team** [comment]
The Herald documentation describes issues for iOS devices that impact the logging of Bluetooth encounters. Herald includes a number of techniques that when used together and in combination provide better Bluetooth communication and more reliable contact detection between devices. The DTA has worked extensively with the creators of Herald to determine how each of the Herald techniques can be leveraged to improve COVIDSafe. Further information on the Herald techniques that are used to provide reliable detection between devices is available on the Herald website.

**Comment by HendX** [comment]
> The DTA has worked extensively with the creators of Herald to determine how each of the Herald techniques can be leveraged to improve COVIDSafe. Further information on the Herald techniques that are used to provide reliable detection between devices is available on the Herald website.

I'm sorry, but in all the information yesterday, the DTA's claim was that it detects "close to 100%" of contacts.

As above, your published graph states "Excellent" performance, which indicates 80-100%. This is an increase from the "25-50%" of the current non-Herald version of COVIDSafe.

It's now unclear what the position of DTA is in regards to the two locked iPhones scenario.

* I have requested evidence to back this claim, so far none has been provided.
* @wabzqem has provided evidence that the performance continues to be unreliable.

This is a fair and reasonable request.

**Comment by yaakov-h** [comment]
I have attempted the same class of test as @wabzqem above and I still have questions about the official test results.

The published test matrix lists logging between two iOS devices, both of which are locked, as "Excellent", which is 80% to 100% of tests.

We know that from previous DTA releases, Senate submissions, and I think FOI requests (?) that the procedure to get these percentages is to run the app for 15 minutes and compare the actual number of logged encounters against the expected number, which is, for some reason, 15, i.e. expecting an average of 1 per minute.

If this new matrix still uses the same methodology as the previous encounter logging tests, is still fundamentally flawed, however I attempted to reproduce these results.

I built the Herald branch, changed the app ID to my own, and signed it with my own developer certificate. I also changed the service UUID to a randomly generated new UUID to avoid interference from current COVIDSafe usage.

I installed the app onto one phone (iPhone 6s w/ iOS 14.2), set it up, and placed it in a microwave oven to act as a faraday cage. I then installed the app onto a second phone (iPhone 12 Pro w/ iOS 14.2.1), set it up, and left it on my desk.

When setting up both phones, I selected the location permission 'Allow While Using App', as iOS 13 and higher does not present the 'Allow Always' option until the app has been used quite a bit. I also turned off Precise location in the prompt, as I suspect many users will do when presented with the location privacy prompt for an app with very little public trust.

After 30 minutes I took the first phone out of the microwave and placed it next to the second phone. This simulates two iOS devices, both locked, that have not yet seen eachother and have now come within Bluetooth range of each-other. I was careful not to wake either device in order to simulate a device that remains inside a handbag or pocket throughout the interaction.

After 30 further minutes I unlocked both devices and checked the debug logs / encounters list.

Each device had recorded 0 handshakes whilst one was inside the microwave, and 26 handshakes in the first 15 minutes afterwards. According to DTA test methodology, _this would be categorized as "Excellent" as it recorded 173% of handshakes._

Additionally, in that one hour, iPhone 12 Pro battery dropped by 2%, but iPhone 6S battery dropped by 19%. (!!)

I suspect that additional device activity such as running an Apple Watch or handling incoming notifications may have woken COVIDSafe on the iPhone 12 Pro in the background, but I cannot say for certain.

I will attempt further testing in the morning.

**Comment by jimmo** [comment]
The Android code disables a Herald feature where an Android device can proxy payloads between two locked iOS devices.

See https://github.com/AU-COVIDSafe/mobile-android/blob/herald/app/src/main/java/au/gov/health/covidsafe/sensor/ble/BLESensorConfiguration.java#L29

The implication here seems to be that the COVIDSafe testing has found that the "get location on wake-up" feature is working well enough. However (as has been mentioned already in this thread) this feature has two major issues:
 - It requires the user to unlock their phone.
 - It's unclear if this is allowed by the app store policies.

Could you please clarify your testing methodology to clear this up.

**Comment by lukeredpath** [comment]
The original NHS COVID app here in the UK was developed by VMWare Pivotal and that one didn’t work due to the same fundamental Bluetooth limitations in iOS. They KNOW it doesn’t and cannot ever work properly. 

My original issue and tests might sound familiar. From 6 months ago. 

https://github.com/nhsx/COVID-19-app-iOS-BETA/issues/2

**Comment by egadsthefuzz** [comment]
Cheers for popping over and adding your experience and hard evidence Luke. Makes for interesting reading and I hope DTA pay attention and at least state how they are attempting to mitigate against the fundamental problems.

**Comment by covidsafe-team** [comment]
Thanks @wabzqem and @yaakov-h for completing tests on our pre-release source code. Thanks @jimmo and others for your observations. We appreciate your contributions.  

The Herald-enabled COVIDSafe app has demonstrated good battery performance. We want to ensure that users can operate the app without concern about their battery usage. Where there was higher iPhone battery use in yaakov-h's test, this is possibly due to the faraday cage impairing the operating system as it attempted to undertake non-COVIDSafe network activities. The iPhone would have operated its radios at full power for longer than normal, leading to the higher battery drain. It is not an indication of COVIDSafe battery use alone. 

Herald was designed to effectively capture close contacts in real world scenarios, and our testing reflects this. It is possible to design simulated tests in lab conditions where Herald does not record any encounters on iOS in background on two locked phones. However, we have observed excellent performance when testing is closer to real world conditions, factoring in technology and human behaviour. In environments where COVIDSafe is intended to be most useful (such as public spaces, large events and other social interactions) it is very unlikely that two iOS phones will not be able to leverage the Herald techniques to bring one of the phones out of background – such as a screen-on event such as receiving a message, a nearby Android device acting as a relay.

Herald includes several techniques that when used together and in combination provide effective Bluetooth communication in their various real-world scenarios. This includes bringing the app out of background mode. Yaakov-h provides a good example when he says, “I suspect that additional device activity such as running an Apple Watch or handling incoming notifications may have woken COVIDSafe on the iPhone 12 Pro in the background, such as when you have an Apple Watch running or are receiving incoming messages.” As the testing above shows, once an iOS device is active, it will wake up surrounding iOS devices. Herald includes a number of techniques that when used together and in combination provide effective Bluetooth communication between devices in their various real world states. 

For a contact tracing app to be effective, it needs to consider the complex balance between epidemiology, technology, and human behavioural science. As a piece of technology, COVIDSafe has a key role in Australia’s COVID-19 response. When the whole picture is assembled, Herald will support Australia's contact tracers with the information they need to maintain our world leading contact tracing processes.

**Comment by HendX** [comment]
Thank you for the considered response to this point, however, this still doesn't contain the details of the testing in order to backup the "Excellent (80-100%)" claim, especially given that earlier this week the language used was "100%".

> it is very unlikely that two iOS phones will not be able to leverage the Herald techniques to bring one of the phones out of background

So how unlikely is it? How did you arrive at the number?

**Comment by HendX** [comment]
What if the person isn't running an Apple Watch?

What if the person doesn't receive an incoming message?

What if app the doesn't wake up?

What if there are too many people in the area that causes the Bluetooth stack exhaustion bug again?

These are not unlikely scenarios, and they need to be quantified accordingly.

> For a contact tracing app to be effective, it needs to consider the complex balance between epidemiology, technology, and human behavioural science.

This is a very fair point, but currently you are no striking the right balance.

The current App Store version pays no consideration to human behaviour aspect of the app, hence why it hasn't worked.

The Herald version pays better consideration to human behaviour (in that it doesn't require the user to baby-sit the app as much). It is great that this is being treated with the serious it deserves, but the technological balance is still not found with the Herald update.

**Comment by ignalex** [comment]
I note that CovidSafe team’s answers are very generic without answering any specific tech questions above.

**Comment by adamc00** [comment]
> For a contact tracing app to be effective, it needs to consider the complex balance between epidemiology, technology, and human behavioural science.

A key aspect of this balance with respect to human behaviour, particularly in this context, is trust. Trust that the information gathered by the app will not be misused, and trust that the best approach is being applied.

> Individuals seek security in Internet applications because trust is often not justified. The more security is guaranteed, the easier it is to have trust. This idea is the focus of Perc and Schneider's (2000) theoretical reasoning: A perceived risk to suffer a loss is counterbalanced by information which reduces the risk. Such information includes contracts, system trust, and more specific trust.

* _https://www.degruyter.com/downloadpdf/journals/auk/26/1/article-p48.xml_

Unfortunately the COVIDSafe model does not prioritise this aspect, but rather prioritises centralised surveillance at the expense of trust. Given that installing and running the COVIDSafe app is voluntary then it can be argued that failing to prioritise trust is a contributing factor to the plateau in uptake. It is certainly a contributing factor to the bad publicity that the COVIDSafe app attracts.

**Comment by yaakov-h** [comment]
For what its worth, I put Herald through a more real-world testing scenario today, but still limiting it to only the "iOS to iOS / Locked to Locked" scenario. I kept the devices asleep as under typical use, when they are woken, they are also unlocked thanks to Face ID, which invalidates the "Locked" scenario.

To test this, I installed the Herald version of COVIDSafe onto two iPhones, activating it on just one phone. I then travelled across town and activated the second phone.

(Both of these devices are fairly clean installations of iOS - unlike my previous test, these are both test devices; none of them are my everyday carry device.)

After quite a while of just being in that area of town I returned home and placed the second iPhone well within range of the first device. After a further 15 minutes I woke both devices, opened COVIDSafe, and checked its logs.

There were _zero_ handshakes on each device throughout the entire period.

This matches @wabzqem's test results previously - 0/15 handshakes within 15 minutes is a 0% score and the very bottom of the "Poor" category.

Whilst @covidsafe-team are somewhat waffling on above about different environmental factors and Android relays (which appear to have been disabled anyway), the fact remains that when constrained to the same test environment as before, the Herald branch fundamentally does not produce the same results that the DTA claim.

If the DTA want to make grand claims about the dynamics of real-world use then it should be backing those up with new test scenarios, detailed test data, and result backed by evidence. Instead, the appear to have simply upgraded every previous test scenario to "Excellent" when this is demonstrably false. On top of that, the metric itself remains fundamentally flawed.

**Comment by jimmo** [comment]
@covidsafe-team 
> it is very unlikely that two iOS phones will not be able to leverage the Herald techniques to bring one of the phones out of background – such as .... a nearby Android device acting as a relay.

Is this feature actually enabled?

https://github.com/AU-COVIDSafe/mobile-android/blob/herald/app/src/main/java/au/gov/health/covidsafe/sensor/ble/BLESensorConfiguration.java#L30

**Comment by covidsafe-team** [comment]
COVIDSafe has been updated with the Herald Protocol. The Herald-enabled COVIDSafe app has demonstrated good battery performance, as the previously provided results indicate. We want to ensure that users can operate the app without concern about their battery usage. We have observed excellent performance when testing in real world conditions, factoring in technology and human behaviour. Further information on the update can be found here: https://www.dta.gov.au/news/covidsafe-uses-herald-protocol-improve-app-performance

**Comment by HendX** [comment]
I don't understand why this issue was closed when it was not even addressed.

> factoring in technology and human behaviour

Given you've arrived at "excellent" between two locked iPhones, it's hard to believe this claim, given what is known about how Bluetooth on iOS works.

In fact, the Herald author, @adamfowleruk, also doesn't want to elaborate on the "two locked iPhones" scenario, which I've repeatedly asked for here: vmware/herald-for-ios#81.

Decisions affecting the health of millions of Australians have been made as a result of these claims. You have a responsibility to be honest and transparent.

**Comment by ignalex** [comment]
Might be the best way to elaborate on this ‘closed’ issue would to involve the mass media...?
